apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 13.7.2
    chart: alertmanager
destination:
  server: https://kubernetes.default.svc
  namespace: observability