apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: topics
  namespace: argocd
spec: 
  destination:
    namespace: topics
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: kafka-topics/base/
    repoURL: "https://github.com/gkoenig/strimzi-jaeger-eval.git"
    targetRevision: HEAD
    directory:
      recurse: false
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    
