apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-kafka
  ## Argo cd namespace, this is required for Argo CD to work
  namespace: argocd
spec:
  destination:
    namespace: confluent
    server: "https://kubernetes.default.svc"
  project: default
  source:
    path: confluent/cp-helm-charts/
    repoURL: "https://github.com/mamonteiro-devops/kafka.git"
    targetRevision: main
    helm:
      releaseName: kafka-release
  syncPolicy:
    syncOptions:
      - CreateNamespace=true


