apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-options: PruneLast=false
  name: guestbook-ui-no-prune
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
