apiVersion: v1
kind: Secret
metadata:
  name: private-repo-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:mabusaa/argocd-example-apps-private.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
     # key goes here  NOTE: dont push secrets into git, use sealed secrets as a solution for secrets in gitops.
    -----END OPENSSH PRIVATE KEY-----
